---
title: "analysis of PC scores for VFT"
output: html_document
---

```{r load demographic info & generate input for analysis}
library(readxl)
path = "/Users/guoqingwang/Google Drive/ProjectWithMartin/fNIRS/fNIRs/demog12_18_15/Data book for Hepatic disease study (10001-10055).xlsx"
data_id = read_excel(path, sheet = 1,skip = 2)
data_MH = read_excel(path, sheet = 2)
data_ADL = read_excel(path, sheet = 3)
data_CCI = read_excel(path, sheet = 4)
data_lab = read_excel(path, sheet = 5)
data_MMSE = read_excel(path, sheet = 6,skip = 1)
data_CAM = read_excel(path, sheet = 7)
data_DRS98 = read_excel(path, sheet = 9)

demog.data = list(id = data_id, MN = data_MH, ADL = data_ADL, CCI = data_CCI, lab = data_lab,
                  MMSE = data_MMSE, CAM = data_CAM, DRS98 = data_DRS98)
save(demog.data,file = "demographicData.rdata")
 
combined_data = data.frame(cam = ifelse(data_id[,24]=="positive",yes = 1,no = 0),
                           gender = ifelse(data_id[,6]=="M",yes = 1, no = 0),
                           age = data_id[,7],
                           YoE = data_MH[,5],
                           meld = data_lab[,21], 
                           cci = as.vector(t(data_CCI[21,3:57])), 
                           inr = data_lab[,20],
                           dsr = data_id[,25],
                           sat = data_id[,23],
                           vft = data_id[,12])
colnames(combined_data) = c("cam","gender","age","YoE","meld","cci","inr","dsr","sat","vft")
demograph = combined_data
demograph$cam = as.factor(demograph$cam)
save(file = "demographicInfo.rdata", demograph)


#combined with score information
s1.l1.vft = vft_dat.results$scores1[,1]
s1.l2.vft = vft_dat.results$scores1[,2]
s1.l3.vft = vft_dat.results$scores1[,3]
s2.l1.vft = vft_dat.results$scores2[,,1]
s2.l2.vft = vft_dat.results$scores2[,,2]
s2.l3.vft = vft_dat.results$scores2[,,3]

library(mice)
#impute s2
score21.vft.imputed = mice(data=t(s2.l1.vft),m = 5, method = "pmm", maxit = 20, seed = 500)
score22.vft.imputed = mice(data=t(s2.l2.vft),m = 5, method = "pmm", maxit = 20, seed = 500)
score23.vft.imputed = mice(data=t(s2.l3.vft),m = 5, method = "pmm", maxit = 20, seed = 500)

s2.l1.vft.imputed = t(complete(score21.vft.imputed))
s2.l2.vft.imputed = t(complete(score22.vft.imputed))
s2.l3.vft.imputed = t(complete(score23.vft.imputed))

load("demographicInfo.rdata")
vft.comb_data = cbind(demograph[-c(51),],s1.l1.vft,s1.l2.vft,s1.l3.vft,s2.l1.vft.imputed,s2.l2.vft.imputed,s2.l3.vft.imputed)
vft.comb_data = vft.comb_data[-33,] # subject 33 has no SAT data, and is excluded from the rest of analysis

save(file = "vft_score_demog.rdata",vft.comb_data)
```

```{r plots}
comb_data = vft.comb_data
comb_data$cam = as.factor(comb_data$cam)
comb_data$gender = as.numeric(comb_data$gender)
library(ggplot2)
library(ggpubr)
s1_age = ggplot(data = comb_data,aes(age,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_sat = ggplot(data = comb_data,aes(sat,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. SAT')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_cam = ggplot(data = comb_data,aes(factor(cam),s1.l1.vft))+geom_boxplot()+labs(title = 'score 1 vs. CAM')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
cam_gender = ggplot(data = comb_data,aes(x=factor(cam),fill=factor(gender)))+geom_bar()+labs(title = 'CAM vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_yoe = ggplot(data = comb_data,aes(factor(YoE),s1.l1.vft))+geom_boxplot() +labs(title = 'score 1 vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_gender = ggplot(data = comb_data,aes(factor(gender),s1.l1.vft))+geom_boxplot()+labs(title = 'score 1 vs. gender')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_DSR = ggplot(data = comb_data,aes(dsr,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. DSR')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_VFT = ggplot(data = comb_data,aes(vft,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. VFT')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_s2 = ggplot(data = comb_data,aes(s1.level2,s1.l1.vft))+geom_point()+labs(title = 'score 1 vs. score 2')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_meld = ggplot(data = comb_data,aes(meld,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. MELD')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_cci = ggplot(data = comb_data,aes(cci,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. CCI')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_inr = ggplot(data = comb_data,aes(inr,s1.l1.vft))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. INR')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

ggarrange(s1_s2, s1_cam, s1_gender, s1_age, s1_sat, s1_VFT, s1_meld, s1_cci, s1_inr,ncol = 3, nrow = 3)

```

