---
title: "fNIRS_delbox_analysis_of_scores"
output: html_document
---
```{r load deomgraphic info}
install.packages(c("mice","readxl","glmnet"))
require(mice)
require(readxl)
loadRData <- function(fileName){
#loads an RData file, and returns it
    load(fileName)
    get(ls()[ls() != "fileName"])
}
dat.result = loadRData('delbox_result.rdata')

missing21 = dat.result$scores2[,,1]
missing22 = dat.result$scores2[,,2]

score21.imputed = mice(data=t(missing21),m = 5, method = "pmm", maxit = 20, seed = 500)
score22.imputed = mice(data=t(missing22),m = 5, method = "pmm", maxit = 20, seed = 500)

names = names1 = names2 = 1:52

for(i in 1:length(names1)){
  names1[i] = paste0("C",names[i],"_1")
  names2[i] = paste0("C",names[i],"_2")
}
s21.impute = t(complete(score21.imputed))
colnames(s21.impute) = names1
s22.impute = t(complete(score22.imputed))
colnames(s22.impute) = names2


corr21 = cor(s21.impute)
image(corr21, axes = F)

dim(dat.result$scores1)
s1.level1 = dat.result$scores1[,1]
s1.level2 = dat.result$scores1[,2]

path = "/Users/guoqingwang/Google Drive/ProjectWithMartin/fNIRS/fNIRs/demog12_18_15/Data book for Hepatic disease study (10001-10055).xlsx"
data_id = read_excel(path, sheet = 1,skip = 2)
data_MH = read_excel(path, sheet = 2)
data_ADL = read_excel(path, sheet = 3)
data_CCI = read_excel(path, sheet = 4)
data_lab = read_excel(path, sheet = 5)
data_MMSE = read_excel(path, sheet = 6,skip = 1)
data_CAM = read_excel(path, sheet = 7)
data_DRS98 = read_excel(path, sheet = 9)

demog.data = list(id = data_id, MH = data_MH, ADL = data_ADL, CCI = data_CCI, lab = data_lab,
                  MMSE = data_MMSE, CAM = data_CAM, DRS98 = data_DRS98)
save(demog.data,file = "demographicData.rdata")

combined_data = data.frame(cam = ifelse(data_id[,24]=="positive",yes = 1,no = 0),
                           gender = ifelse(data_id[,6]=="M",yes = 1, no = 0),
                           age = data_id[,7],
                           YoE = data_MH[,5],
                           meld = data_lab[,21], 
                           cci = as.vector(t(data_CCI[21,3:57])), 
                           inr = data_lab[,20],
                           dsr = data_id[,25],
                           sat = data_id[,23],
                           vft = data_id[,12])
colnames(combined_data) = c("cam","gender","age","YoE","meld","cci","inr","dsr","sat","vft")
combined_data = combined_data[-c(33,51),] #remove empty subjects delbox

#combined_data = combined_data[-c(51),] #remove empty subjects VFT
comb_data = cbind(combined_data,s1.level1,s1.level2,s21.impute,s22.impute)
#save(comb_data,file = "delbox_scores_demog.rdata")
```

```{r plots and regression SVM}
comb_data = loadRData("delbox_scores_demog.rdata")

comb_data$cam = as.factor(comb_data$cam)
comb_data$gender = as.numeric(comb_data$gender)

delbox.score.data.combined = cbind(combined_data,s.level1,s21.impute,s22.impute)
library(ggplot2)
library(ggpubr)
s1_age = ggplot(data = comb_data,aes(age,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_sat = ggplot(data = comb_data,aes(sat,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. SAT')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_cam = ggplot(data = comb_data,aes(factor(cam),s1.level1))+geom_boxplot()+labs(title = 'score 1 vs. CAM')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
cam_gender = ggplot(data = comb_data,aes(x=factor(cam),fill=factor(gender)))+geom_bar()+labs(title = 'CAM vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_yoe = ggplot(data = comb_data,aes(factor(YoE),s1.level1))+geom_boxplot() +labs(title = 'score 1 vs. age')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_gender = ggplot(data = comb_data,aes(factor(gender),s1.level1))+geom_boxplot()+labs(title = 'score 1 vs. gender')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_DSR = ggplot(data = comb_data,aes(dsr,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. DSR')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_VFT = ggplot(data = comb_data,aes(vft,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. VFT')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_s2 = ggplot(data = comb_data,aes(s1.level2,s1.level1))+geom_point()+labs(title = 'score 1 vs. score 2')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_meld = ggplot(data = comb_data,aes(meld,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. MELD')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

s1_cci = ggplot(data = comb_data,aes(cci,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. CCI')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))
s1_inr = ggplot(data = comb_data,aes(inr,s1.level1))+geom_point()+geom_smooth()+labs(title = 'score 1 vs. INR')+theme(axis.title.x=element_blank(),axis.title.y = element_blank(),plot.title = element_text(hjust = 0.5))

ggarrange(s1_s2, s1_cam, s1_gender, s1_age, s1_sat, s1_VFT, s1_meld, s1_cci, s1_inr,ncol = 3, nrow = 3)

# apply svm 

library(e1071)
set.seed(1)
comb_data = loadRData("delbox_scores_demog.rdata")
comb_data$cam = as.factor(comb_data$cam)
comb_data$gender = as.numeric(comb_data$gender)
inputData = data.frame(gender = comb_data$gender,scale(comb_data[,-c(1,2)]))

svm_tune = tune(svm, train.x = inputData, train.y = comb_data$cam,kernel="linear", ranges=list(epsilon = seq(0,1,0.1), cost = 2^(2:9)))
svm_tune$best.parameters
summary(svm_tune)
svmfit1 = svm_tune$best.model
pred <- predict(svmfit1,inputData)
table(pred,comb_data$cam)

weigths = t(svmfit1$coefs) %*% svmfit1$SV

comb_data$cam = as.factor(comb_data$cam)
comb_data$gender = as.numeric(comb_data$gender)-1
inputData.Brain = data.frame(scale(comb_data[,-c(1:10)]))

svm_tune = tune(svm, train.x = inputData.Brain, train.y = comb_data$cam,kernel="linear", ranges=list(epsilon = seq(0,1,0.1), cost = 2^(2:9)),decision.values=T)
svmfit1.brain = svm_tune$best.model

pred <- predict(svmfit1.brain,inputData.Brain)
fitted=attributes(predict(svmfit1.brain,inputData.Brain,decision.values=TRUE))$decision.values

table(pred,true=comb_data$cam)
weigths.Brain = t(svmfit1.brain$coefs) %*% svmfit1.brain$SV
svm_tune$best.parameters

write.csv(x = weigths.Brain[3:54],file = "delbox_brain_1.csv")
write.csv(x = weigths.Brain[55:106],file = "delbox_brain_2.csv")
write.csv(x = weigths[9+3:54],file = "delbox_overall_1.csv")
write.csv(x = weigths[9+55:106],file = "delbox_overall_2.csv")



set.seed(1)
# Brain info only
variable2 = 2:10
variables1 = 1
variables = 1:10# 1:10 means brain only, 1 means including demographic info
nsubj = 53
pred.delbox.brain = 1:nsubj
pred.delbox.demo = 1:nsubj
pred.delbox = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitBrainCV = svm(x = train[,-variables], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp = predict(fitBrainCV,test[,-variables], probability = TRUE)
  pred.delbox.brain[i] = attr(temp, "probabilities")[,2]
  fitsvm = svm(x = train[,-variables1], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp1 = predict(fitsvm,test[,-variables1],decision.values =TRUE,probability = TRUE)
  pred.delbox[i] = attr(temp1, "probabilities")[,2]
  fitsvm.demo = svm(x = train[,variable2], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp2 = predict(fitsvm.demo,test[,variable2], decision.values =TRUE,probability = TRUE)
  pred.delbox.demo[i] = attr(temp2, "probabilities")[,2]
}
library(pROC)
par(mfrow = c(1,1))
roc1.delbox = roc(comb_data$cam~pred.delbox.brain[1:nsubj])
roc2.delbox = roc(comb_data$cam~pred.delbox[1:nsubj])
roc3.delbox = roc(comb_data$cam~pred.delbox.demo[1:nsubj])


plot(roc1.delbox,main = paste("ROC curve (SAT SVM)"))
lines(roc2.delbox,col = 2)
lines(roc3.delbox,col = 3)

auc1 = round(auc(roc1.delbox),3);ci1.delbox = round(as.numeric(ci(roc1.delbox)),3)
auc2 = round(auc(roc2.delbox),3);ci2.delbox = round(as.numeric(ci(roc2.delbox)),3)
auc3 = round(auc(roc3.delbox),3);ci3.delbox = round(as.numeric(ci(roc3.delbox)),3)
#legend("bottomright",legend = c(paste("Brain info only, AUC = ", auc1), paste("Demographic and brain info, AUC = ", auc2)), col = c(1,2),pch = "-",cex=0.7)

legend("bottomright",legend = c(paste("Brain info only, AUC = ", auc1,'CI (', ci1.delbox[1],',',ci1.delbox[3],')'), 
                                paste("Demographic and brain info, AUC = ", auc2,'CI (', ci2.delbox[1],',',ci2.delbox[3],')'),
                                paste("Demographic info only, AUC = ", auc3,'CI (', ci3.delbox[1],',',ci3.delbox[3],')')), 
       col = c(1,2,3),pch = "-",cex=0.7)

####### remove the Level 1 scores

variable2 = 2:10
variables1 = c(1,11,12)
variables = c(1:12,65:116)# 1:10 means brain only, 1 means including demographic info
nsubj = 53
pred.delbox.brain = 1:nsubj
pred.delbox.demo = 1:nsubj
pred.delbox = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitBrainCV = svm(x = train[,-variables], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp = predict(fitBrainCV,test[,-variables], decision.values =TRUE, probability = TRUE)
  pred.delbox.brain[i] = attr(temp, "probabilities")[,2]
  fitsvm = svm(x = train[,-variables1], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp1 = predict(fitsvm,test[,-variables1],decision.values =TRUE,probability = TRUE)
  pred.delbox[i] = attr(temp1, "probabilities")[,2]
  fitsvm.demo = svm(x = train[,variable2], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
  temp2 = predict(fitsvm.demo,test[,variable2], decision.values =TRUE,probability = TRUE)
  pred.delbox.demo[i] = attr(temp2, "probabilities")[,2]
}


library(pROC)
par(mfrow = c(1,1))
plot(roc(comb_data$cam~pred.delbox.brain[1:nsubj]),
     main = paste("ROC curve (SAT SVM)"))
lines(roc(comb_data$cam~pred.delbox[1:nsubj]),col = 2)
lines(roc(comb_data$cam~pred.delbox.demo[1:nsubj]),col = 3)

auc1 = round(auc(roc(comb_data$cam~pred.delbox.brain[1:nsubj])),3)
auc2 = round(auc(roc(comb_data$cam~pred.delbox[1:nsubj])),3)
auc3 = round(auc(roc(comb_data$cam~pred.delbox.demo[1:nsubj])),3)
legend("bottomright",legend = c(paste("Brain info only, AUC = ", auc1), paste("Demographic and brain info, AUC = ", auc2)), col = c(1,2),pch = "-",cex=0.7)

```


```{r tests}
#### USE ROCR package
library(ROCR)
rocperf=function(pred, truth, ...){
  predob = prediction (pred, truth)
  perf = performance (predob , "tpr", "fpr") 
  return(perf)
  }

variables = 1:10# 1:10 means brain only, 1 means including demographic info
nsubj = 53
fitted.delbox.brain = 1:nsubj
fitted.delbox.all = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitBrainCV = svm(x = train[,-variables], y = train$cam, kernel="radial",epsilon = 0,cost = 4,probability = T)
    fitsvm = svm(x = train[,-variables1], y = train$cam, kernel="radial",epsilon = 0,cost = 4,probability = T)
  temp = predict(fitBrainCV,test[,-variables], decision.values =TRUE, probability = TRUE)
  temp.all=predict(fitsvm,test[,-variables1], decision.values =TRUE, probability = TRUE)
  fitted.delbox.brain[i] = attributes(temp)$decision.values
  fitted.delbox.all[i] = attributes(temp.all)$decision.values
}

rocplot(fitted.delbox.brain, comb_data$cam,col = 1)
rocplot(fitted.delbox.all, comb_data$cam, add = T, col = 2)
performance(prediction(fitted.delbox.brain, comb_data$cam),'auc')@"y.values" #0.57
performance(prediction(fitted.delbox.all, comb_data$cam),'auc')@"y.values"#0.75
# random frorest trial

library(randomForest)
rftune = tuneRF(x = inputData, y = comb_data$cam,stepFactor = 1.5, improve = 1e-5, ntreeTry = 500)


fitrf = randomForest(x = inputData, y = comb_data$cam, mtry = 22)
cl.rf = predict(fitrf, inputData, type = "class")
pr.rf = predict(fitrf, inputData, type = "prob")[,2]
table(pred = cl.rf, true = comb_data$cam)

set.seed(2017)
variables = 1:10# 1:10 means brain only, 1 means including demographic info
nsubj = 53
pred = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitrf = randomForest(x = train[,-variables], y = train$cam, mtry=22)
  pred[i] = predict(fitrf,test[,-variables], type = "prob")[,2]
}
variables1 = 1# 1:10 means brain only, 1 means including demographic info
nsubj = 53
pred1 = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitrf = randomForest(x = train[,-variables1], y = train$cam, mtry=22)
  pred1[i] = predict(fitrf,test[,-variables1], type = "prob")[,2]
}
variables2 = 2:10# 1:10 means brain only, 1 means including demographic info
nsubj = 53
pred2 = 1:nsubj
for(i in 1:nsubj){
  test = comb_data[i,]
  train = comb_data[-i,]
  fitrf = randomForest(x = train[,variables2], y = train$cam, mtry=22)
  pred2[i] = predict(fitrf,test[,variables2], type = "prob")[,2]
}

library(pROC)
par(mfrow = c(1,1))
plot(roc(comb_data$cam~pred[1:nsubj]),
     main = paste("ROC curve"), col = 1)
lines(roc(comb_data$cam~pred1[1:nsubj]),col = 2)
lines(roc(comb_data$cam~pred2[1:nsubj]),col = 3)
auc1 = round(auc(roc(comb_data$cam~pred[1:nsubj])),3)
auc2 = round(auc(roc(comb_data$cam~pred1[1:nsubj])),3)
auc3 = round(auc(roc(comb_data$cam~pred2[1:nsubj])),3)

legend("bottomright",legend = c(paste("Demographic and brain info, AUC = ", auc2),paste("Brain info only, AUC = ", auc1)), col = c(2,1,3),pch = "-",cex=0.7)

legend("bottomright",legend = c(paste("Demographic and brain info, AUC = ", auc2),paste("Brain info only, AUC = ", auc1),paste("Demographic info only, AUC = ", auc3)), col = c(2,1,3),pch = "-",cex=0.7)

# variables = 1:10# 1:10 means brain only, 1 means including demographic info
# nsubj = 53
# pred = 1:nsubj
# for(i in 1:nsubj){
#   test = comb_data[i,]
#   train = comb_data[-i,]
#   fitBrainCV = svm(x = train[,-variables], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
#   temp = predict(fitBrainCV,test[,-variables], decision.values =TRUE, probability = TRUE)
#   pred[i] = attr(temp, "decision.values")
# }
# 
# variables1 = 1# 1:10 means brain only, 1 means including demographic info
# nsubj = 53
# pred1 = 1:nsubj
# for(i in 1:nsubj){
#   test = comb_data[i,]
#   train = comb_data[-i,]
#   fitsvm = svm(x = train[,-variables1], y = train$cam, kernel="linear",epsilon = 0,cost = 4,probability = T)
#   temp = predict(fitsvm,test[,-variables1],decision.values =TRUE,probability = TRUE)
#   pred1[i] = attr(temp, "decision.values")
# }
# 
# rocplot(pred1,comb_data$cam)
```
